window.CHANA_CATALOG_BACKUP = [
  {
    "id": 1,
    "name": "Chilaquiles de la Abuela",
    "category": "Desayunos",
    "price": 125,
    "emoji": "🍳",
    "image": "",
    "description": "Totopos, salsa de la casa, crema, queso, cebolla y dos huevos.",
    "active": true,
    "order": 1
  },
  {
    "id": 2,
    "name": "Omelette Chana",
    "category": "Desayunos",
    "price": 135,
    "emoji": "🥚",
    "image": "",
    "description": "Tres huevos, jamón, queso, vegetales y frijoles de la olla.",
    "active": true,
    "order": 2
  },
  {
    "id": 3,
    "name": "Hot Cakes Caseros",
    "category": "Desayunos",
    "price": 105,
    "emoji": "🥞",
    "image": "",
    "description": "Tres piezas esponjosas con fruta, mantequilla y miel.",
    "active": true,
    "order": 3
  },
  {
    "id": 4,
    "name": "Enchiladas de la Casa",
    "category": "Comidas",
    "price": 155,
    "emoji": "🫔",
    "image": "",
    "description": "Cuatro enchiladas con pollo, arroz, frijoles, crema y queso.",
    "active": true,
    "order": 4
  },
  {
    "id": 5,
    "name": "Milanesa con Papas",
    "category": "Comidas",
    "price": 175,
    "emoji": "🍽️",
    "image": "",
    "description": "Milanesa doradita, papas, ensalada fresca y arroz.",
    "active": true,
    "order": 5
  },
  {
    "id": 6,
    "name": "Tacos Dorados",
    "category": "Antojitos",
    "price": 115,
    "emoji": "🌮",
    "image": "",
    "description": "Cinco tacos de papa o pollo con lechuga, crema y salsa.",
    "active": true,
    "order": 6
  },
  {
    "id": 7,
    "name": "Quesadilla Especial",
    "category": "Antojitos",
    "price": 90,
    "emoji": "🧀",
    "image": "",
    "description": "Tortilla de harina, queso, carne asada y guacamole.",
    "active": true,
    "order": 7
  },
  {
    "id": 8,
    "name": "Tostada de Ceviche",
    "category": "Coctelería",
    "price": 85,
    "emoji": "🍤",
    "image": "",
    "description": "Ceviche fresco, aguacate, pepino y salsa de la casa.",
    "active": true,
    "order": 8
  },
  {
    "id": 9,
    "name": "Cóctel de Camarón",
    "category": "Coctelería",
    "price": 175,
    "emoji": "🦐",
    "image": "",
    "description": "Camarón, tomate, cebolla, pepino, aguacate y limón.",
    "active": true,
    "order": 9
  },
  {
    "id": 10,
    "name": "Flan de la Abuela",
    "category": "Postres",
    "price": 65,
    "emoji": "🍮",
    "image": "",
    "description": "Flan casero de vainilla con caramelo tradicional.",
    "active": true,
    "order": 10
  },
  {
    "id": 11,
    "name": "Pastel del Día",
    "category": "Postres",
    "price": 75,
    "emoji": "🍰",
    "image": "",
    "description": "Pregunta por nuestro sabor recién preparado.",
    "active": true,
    "order": 11
  },
  {
    "id": 12,
    "name": "Agua Fresca",
    "category": "Bebidas",
    "price": 40,
    "emoji": "🥤",
    "image": "",
    "description": "Vaso grande. Pregunta por los sabores del día.",
    "active": true,
    "order": 12
  },
  {
    "id": 13,
    "name": "La María",
    "category": "Coctelería",
    "price": 129,
    "emoji": "🍹",
    "image": "",
    "description": "Guanábana, infusión cítrica, cereza y agua mineral.",
    "active": true,
    "order": 13
  },
  {
    "id": 14,
    "name": "Místico",
    "category": "Coctelería",
    "price": 129,
    "emoji": "🍹",
    "image": "",
    "description": "Maracuyá, menta, infusión cítrica, jarabe natural y agua mineral.",
    "active": true,
    "order": 14
  },
  {
    "id": 15,
    "name": "Xolo",
    "category": "Coctelería",
    "price": 129,
    "emoji": "🍹",
    "image": "",
    "description": "Frutos rojos, mezcla de cítricos y agua tónica.",
    "active": true,
    "order": 15
  },
  {
    "id": 16,
    "name": "Jaguar",
    "category": "Coctelería",
    "price": 129,
    "emoji": "🍹",
    "image": "",
    "description": "Durazno, menta, mango, cítricos y agua tónica.",
    "active": true,
    "order": 16
  },
  {
    "id": 17,
    "name": "Alebrije",
    "category": "Coctelería",
    "price": 129,
    "emoji": "🍹",
    "image": "",
    "description": "Kiwi, limón amarillo, toque secreto de la abuela y agua mineral.",
    "active": true,
    "order": 17
  },
  {
    "id": 18,
    "name": "Bajío",
    "category": "Coctelería",
    "price": 129,
    "emoji": "🍹",
    "image": "",
    "description": "Fresa, kiwi, naranja, limón verde y azúcar morena.",
    "active": true,
    "order": 18
  },
  {
    "id": 19,
    "name": "Mojito Virgen",
    "category": "Coctelería",
    "price": 129,
    "emoji": "🍹",
    "image": "",
    "description": "Limón, menta, jarabe y agua mineral. Sabores: limón, maracuyá, frutos rojos, kiwi, tamarindo, mango, fresa o durazno.",
    "active": true,
    "order": 19
  },
  {
    "id": 20,
    "name": "Jarra grande de mocktel",
    "category": "Coctelería",
    "price": 280,
    "emoji": "🍹",
    "image": "",
    "description": "Jarra grande de mocktel para compartir.",
    "active": true,
    "order": 20
  },
  {
    "id": 21,
    "name": "Mateo Martini",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Jack Daniel's, Amaretto Disaronno, maracuyá y cítricos.",
    "active": true,
    "order": 21
  },
  {
    "id": 22,
    "name": "Catrina",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Mezcal, licor de naranja, jamaica, maracuyá y agua quina.",
    "active": true,
    "order": 22
  },
  {
    "id": 23,
    "name": "Margarita Mexicana",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Tequila blanco, Controy, guanábana, naranja y chile serrano. Frozen.",
    "active": true,
    "order": 23
  },
  {
    "id": 24,
    "name": "Frontera",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Vodka de tamarindo, mango, limón, azúcar morena, agua mineral y tónica.",
    "active": true,
    "order": 24
  },
  {
    "id": 25,
    "name": "Diegos",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Ginebra, manzana verde, kiwi, azúcar mascabado, limón amarillo y agua mineral.",
    "active": true,
    "order": 25
  },
  {
    "id": 26,
    "name": "El Santo",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Vodka, Hypnotiq, durazno, manzana y agua tónica.",
    "active": true,
    "order": 26
  },
  {
    "id": 27,
    "name": "Nahual Rojo",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Mezcal, Licor 43, frutos rojos, naranja y escarchado de tamarindo y Tajín.",
    "active": true,
    "order": 27
  },
  {
    "id": 28,
    "name": "Martini Azteca",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Ron Malibu, Licor 43, guanábana, maracuyá, naranja y jarabe. Frapeado.",
    "active": true,
    "order": 28
  },
  {
    "id": 29,
    "name": "Bebida de la Frida",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Tequila reposado, licor de naranja, albahaca, cítricos y escarchado de tamarindo y Tajín.",
    "active": true,
    "order": 29
  },
  {
    "id": 30,
    "name": "Chente",
    "category": "Mixología",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Tequila, Controy, mango, limón, jarabe y chile serrano. Frapeado.",
    "active": true,
    "order": 30
  },
  {
    "id": 31,
    "name": "Carajillo de Olla",
    "category": "Mixología",
    "price": 139,
    "emoji": "☕",
    "image": "",
    "description": "Café de olla caliente con Licor 43 o mezcal.",
    "active": true,
    "order": 31
  },
  {
    "id": 32,
    "name": "Aguas del día",
    "category": "Bebidas",
    "price": 55,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 32
  },
  {
    "id": 33,
    "name": "Jugo de naranja",
    "category": "Bebidas",
    "price": 69,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 33
  },
  {
    "id": 34,
    "name": "Jugo verde",
    "category": "Bebidas",
    "price": 70,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 34
  },
  {
    "id": 35,
    "name": "Soda",
    "category": "Bebidas",
    "price": 45,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 35
  },
  {
    "id": 36,
    "name": "Café de olla",
    "category": "Bebidas",
    "price": 59,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 36
  },
  {
    "id": 37,
    "name": "Café americano",
    "category": "Bebidas",
    "price": 55,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 37
  },
  {
    "id": 38,
    "name": "Café lechero",
    "category": "Bebidas",
    "price": 80,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 38
  },
  {
    "id": 39,
    "name": "Tisana de sabores",
    "category": "Bebidas",
    "price": 79,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 39
  },
  {
    "id": 40,
    "name": "Chocolate caliente",
    "category": "Bebidas",
    "price": 65,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 40
  },
  {
    "id": 41,
    "name": "Avena en vaso",
    "category": "Bebidas",
    "price": 55,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 41
  },
  {
    "id": 42,
    "name": "Botella de agua",
    "category": "Bebidas",
    "price": 30,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 42
  },
  {
    "id": 43,
    "name": "Jarra de agua del día",
    "category": "Bebidas",
    "price": 169,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 43
  },
  {
    "id": 44,
    "name": "Jarra de jugo de naranja",
    "category": "Bebidas",
    "price": 190,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 44
  },
  {
    "id": 45,
    "name": "Limonada natural",
    "category": "Bebidas",
    "price": 60,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 45
  },
  {
    "id": 46,
    "name": "Limonada mineral",
    "category": "Bebidas",
    "price": 65,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 46
  },
  {
    "id": 47,
    "name": "Jarra de limonada natural",
    "category": "Bebidas",
    "price": 179,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 47
  },
  {
    "id": 48,
    "name": "Jarra de limonada mineral",
    "category": "Bebidas",
    "price": 189,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 48
  },
  {
    "id": 49,
    "name": "Naranjada natural",
    "category": "Bebidas",
    "price": 65,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 49
  },
  {
    "id": 50,
    "name": "Naranjada mineral",
    "category": "Bebidas",
    "price": 69,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 50
  },
  {
    "id": 51,
    "name": "Jarra de naranjada natural",
    "category": "Bebidas",
    "price": 179,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 51
  },
  {
    "id": 52,
    "name": "Jarra de naranjada mineral",
    "category": "Bebidas",
    "price": 189,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 52
  },
  {
    "id": 53,
    "name": "Licuado de plátano",
    "category": "Bebidas",
    "price": 65,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 53
  },
  {
    "id": 54,
    "name": "Licuado de fresa",
    "category": "Bebidas",
    "price": 69,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 54
  },
  {
    "id": 55,
    "name": "Choco milk",
    "category": "Bebidas",
    "price": 55,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 55
  },
  {
    "id": 56,
    "name": "Malteada de fresa",
    "category": "Bebidas",
    "price": 79,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 56
  },
  {
    "id": 57,
    "name": "Malteada de vainilla",
    "category": "Bebidas",
    "price": 79,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 57
  },
  {
    "id": 58,
    "name": "Malteada de chocolate",
    "category": "Bebidas",
    "price": 79,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 58
  },
  {
    "id": 59,
    "name": "Malteada de Oreo",
    "category": "Bebidas",
    "price": 79,
    "emoji": "🥤",
    "image": "",
    "description": "Bebida preparada al momento.",
    "active": true,
    "order": 59
  },
  {
    "id": 60,
    "name": "Carajillo",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Licor 43 y espresso.",
    "active": true,
    "order": 60
  },
  {
    "id": 61,
    "name": "Martini Espresso",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Vodka, espresso, jarabe y Baileys.",
    "active": true,
    "order": 61
  },
  {
    "id": 62,
    "name": "Martini Cosmopolitan",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Vodka, cítricos y arándanos.",
    "active": true,
    "order": 62
  },
  {
    "id": 63,
    "name": "Old Fashioned",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🥃",
    "image": "",
    "description": "Whisky, licor de angostura y naranja.",
    "active": true,
    "order": 63
  },
  {
    "id": 64,
    "name": "Sangría de la Casa",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍷",
    "image": "",
    "description": "Limón amarillo, jarabe, agua mineral y vino rosado, blanco o tinto.",
    "active": true,
    "order": 64
  },
  {
    "id": 65,
    "name": "Mojito Cubano",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍹",
    "image": "",
    "description": "Ron, hierbabuena, limón amarillo, jarabe y agua mineral. Varios sabores.",
    "active": true,
    "order": 65
  },
  {
    "id": 66,
    "name": "Margarita en Rocas o Frozen",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍹",
    "image": "",
    "description": "Tequila, licor de naranja, limón, jarabe y escarchado de tamarindo y Tajín.",
    "active": true,
    "order": 66
  },
  {
    "id": 67,
    "name": "Mezcalita en Rocas o Frozen",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍹",
    "image": "",
    "description": "Mezcal, licor de naranja, limón, jarabe y escarchado de tamarindo y Tajín.",
    "active": true,
    "order": 67
  },
  {
    "id": 68,
    "name": "Piña Colada Clásica",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍹",
    "image": "",
    "description": "Ron, crema de coco, piña y Carnation.",
    "active": true,
    "order": 68
  },
  {
    "id": 69,
    "name": "Mimosa TJ",
    "category": "Bebidas clásicas",
    "price": 129,
    "emoji": "🥂",
    "image": "",
    "description": "Vino espumoso con mezclador natural de naranja, maracuyá, durazno, kiwi o frutos rojos.",
    "active": true,
    "order": 69
  },
  {
    "id": 70,
    "name": "Jarra de Sangría de la Casa",
    "category": "Bebidas clásicas",
    "price": 289,
    "emoji": "🍷",
    "image": "",
    "description": "Limón, jarabe, agua mineral y vino rosado, blanco o tinto.",
    "active": true,
    "order": 70
  },
  {
    "id": 71,
    "name": "Daiquiri",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍹",
    "image": "",
    "description": "Ron, limón y jarabe. Varios sabores.",
    "active": true,
    "order": 71
  },
  {
    "id": 72,
    "name": "Gin-Tonic",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Ginebra y agua tónica. Varios sabores.",
    "active": true,
    "order": 72
  },
  {
    "id": 73,
    "name": "Bloody Mary",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍸",
    "image": "",
    "description": "Vodka, jugo de tomate, limón, Tabasco y escarchado con Tajín y tamarindo.",
    "active": true,
    "order": 73
  },
  {
    "id": 74,
    "name": "Paloma",
    "category": "Bebidas clásicas",
    "price": 139,
    "emoji": "🍹",
    "image": "",
    "description": "Tequila reposado, limón, toronja y jarabe natural.",
    "active": true,
    "order": 74
  },
  {
    "id": 75,
    "name": "Don Julio Blanco",
    "category": "Tequila",
    "price": 109,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 75
  },
  {
    "id": 76,
    "name": "Don Julio Reposado",
    "category": "Tequila",
    "price": 119,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 76
  },
  {
    "id": 77,
    "name": "Don Julio 70",
    "category": "Tequila",
    "price": 159,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 77
  },
  {
    "id": 78,
    "name": "Maestro Dobel Cristalino Diamante",
    "category": "Tequila",
    "price": 149,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 78
  },
  {
    "id": 79,
    "name": "Tequila Don Ramón Blanco",
    "category": "Tequila",
    "price": 139,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 79
  },
  {
    "id": 80,
    "name": "Tequila Don Ramón Reposado",
    "category": "Tequila",
    "price": 139,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 80
  },
  {
    "id": 81,
    "name": "Tequila Tradicional Reposado",
    "category": "Tequila",
    "price": 109,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 81
  },
  {
    "id": 82,
    "name": "Tequila Centenario Reposado",
    "category": "Tequila",
    "price": 109,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 82
  },
  {
    "id": 83,
    "name": "Tequila Eterno Blanco",
    "category": "Tequila",
    "price": 109,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 83
  },
  {
    "id": 84,
    "name": "Tequila 1800 Añejo",
    "category": "Tequila",
    "price": 139,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de tequila.",
    "active": true,
    "order": 84
  },
  {
    "id": 85,
    "name": "Bombay",
    "category": "Ginebra",
    "price": 139,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de ginebra.",
    "active": true,
    "order": 85
  },
  {
    "id": 86,
    "name": "Etiqueta Roja",
    "category": "Whisky",
    "price": 129,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de whisky.",
    "active": true,
    "order": 86
  },
  {
    "id": 87,
    "name": "Etiqueta Negra",
    "category": "Whisky",
    "price": 149,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de whisky.",
    "active": true,
    "order": 87
  },
  {
    "id": 88,
    "name": "Etiqueta Doble Negra",
    "category": "Whisky",
    "price": 169,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de whisky.",
    "active": true,
    "order": 88
  },
  {
    "id": 89,
    "name": "Buchanan's 12",
    "category": "Whisky",
    "price": 149,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de whisky.",
    "active": true,
    "order": 89
  },
  {
    "id": 90,
    "name": "Buchanan's 18",
    "category": "Whisky",
    "price": 169,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de whisky.",
    "active": true,
    "order": 90
  },
  {
    "id": 91,
    "name": "Buchanan's Master",
    "category": "Whisky",
    "price": 189,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de whisky.",
    "active": true,
    "order": 91
  },
  {
    "id": 92,
    "name": "Buchanan's Pineapple",
    "category": "Whisky",
    "price": 149,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de whisky.",
    "active": true,
    "order": 92
  },
  {
    "id": 93,
    "name": "Chivas Regal 12",
    "category": "Whisky",
    "price": 149,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de whisky.",
    "active": true,
    "order": 93
  },
  {
    "id": 94,
    "name": "Absolut Azul",
    "category": "Vodka",
    "price": 129,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de vodka.",
    "active": true,
    "order": 94
  },
  {
    "id": 95,
    "name": "Malibu",
    "category": "Ron",
    "price": 119,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de ron.",
    "active": true,
    "order": 95
  },
  {
    "id": 96,
    "name": "Captain Morgan Spiced",
    "category": "Ron",
    "price": 119,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de ron.",
    "active": true,
    "order": 96
  },
  {
    "id": 97,
    "name": "Bacardí Blanco",
    "category": "Ron",
    "price": 119,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de ron.",
    "active": true,
    "order": 97
  },
  {
    "id": 98,
    "name": "400 Conejos Joven",
    "category": "Mezcal",
    "price": 129,
    "emoji": "🥃",
    "image": "",
    "description": "Copa de mezcal.",
    "active": true,
    "order": 98
  },
  {
    "id": 99,
    "name": "Hypnotiq",
    "category": "Licores",
    "price": 119,
    "emoji": "🥃",
    "image": "",
    "description": "Licor por copeo.",
    "active": true,
    "order": 99
  },
  {
    "id": 100,
    "name": "Licor 43",
    "category": "Licores",
    "price": 109,
    "emoji": "🥃",
    "image": "",
    "description": "Licor por copeo.",
    "active": true,
    "order": 100
  },
  {
    "id": 101,
    "name": "Amaretto Disaronno",
    "category": "Licores",
    "price": 109,
    "emoji": "🥃",
    "image": "",
    "description": "Licor por copeo.",
    "active": true,
    "order": 101
  },
  {
    "id": 102,
    "name": "Cabernet Sauvignon",
    "category": "Vino tinto",
    "price": 109,
    "emoji": "🍷",
    "image": "",
    "description": "Copa de vino tinto.",
    "active": true,
    "order": 102
  },
  {
    "id": 103,
    "name": "Zinfandel",
    "category": "Vino rosado",
    "price": 109,
    "emoji": "🍷",
    "image": "",
    "description": "Copa de vino rosado.",
    "active": true,
    "order": 103
  },
  {
    "id": 104,
    "name": "Chardonnay",
    "category": "Vino blanco",
    "price": 109,
    "emoji": "🍷",
    "image": "",
    "description": "Copa de vino blanco.",
    "active": true,
    "order": 104
  },
  {
    "id": 105,
    "name": "Chambrule",
    "category": "Vino espumoso",
    "price": 109,
    "emoji": "🥂",
    "image": "",
    "description": "Copa de vino espumoso.",
    "active": true,
    "order": 105
  }
];
